image: openjdk:8

pipelines:
  default:
    - step:
        caches:
          - gradle
        script:
          - bash ./gradlew build
  branches:
    develop:
      - step:
          name: Check
          caches:
            - gradle
          script:
            - bash ./gradlew check
